# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7322ec18360b9ea45d604766a79e0b65c4750d97fe587aade7c2332cd28a4cc8a936c18046912b7db9f4772fa90124dc71cfddf49c7ff327c8a1a12ed80e3610

test:
  secret_key_base: 879bb16019fc07402e7b88d1a8257629529555b01604f4c588e9ad8f133467808fe5977d05708e1eb0ce799448d7223a547e4871d62cc831656d96f0a2ad650c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
